./runProgram.sh -f input/chain4-conflicts.xml -a ac1 >> output.csv &&
./runProgram.sh -f input/chain4-conflicts.xml -a ac3 >> output.csv &&
./runProgram.sh -f input/ColK4-conflicts.xml -a ac1 >> output.csv &&
./runProgram.sh -f input/ColK4-conflicts.xml -a ac3 >> output.csv &&
./runProgram.sh -f input/3queens-conflicts.xml -a ac1 >> output.csv &&
./runProgram.sh -f input/3queens-conflicts.xml -a ac3 >> output.csv &&
./runProgram.sh -f input/3queens-intension.xml -a ac1 >> output.csv &&
./runProgram.sh -f input/3queens-intension.xml -a ac3 >> output.csv &&
./runProgram.sh -f input/4queens-conflicts.xml -a ac1 >> output.csv &&
./runProgram.sh -f input/4queens-conflicts.xml -a ac3 >> output.csv &&
./runProgram.sh -f input/4queens-supports.xml -a ac1 >> output.csv &&
./runProgram.sh -f input/4queens-supports.xml -a ac3 >> output.csv &&
./runProgram.sh -f input/5queens-intension.xml -a ac1 >> output.csv &&
./runProgram.sh -f input/5queens-intension.xml -a ac3 >> output.csv &&
./runProgram.sh -f input/6queens-conflicts.xml -a ac1 >> output.csv &&
./runProgram.sh -f input/6queens-conflicts.xml -a ac3 >> output.csv &&
./runProgram.sh -f input/6queens-intension.xml -a ac1 >> output.csv &&
./runProgram.sh -f input/6queens-intension.xml -a ac3 >> output.csv &&
./runProgram.sh -f input/ColAustralia-conflicts.xml -a ac1 >> output.csv &&
./runProgram.sh -f input/ColAustralia-conflicts.xml -a ac3 >> output.csv &&
./runProgram.sh -f input/ColAustralia-intension.xml -a ac1 >> output.csv &&
./runProgram.sh -f input/ColAustralia-intension.xml -a ac3 >> output.csv &&
./runProgram.sh -f input/zebra-extension.xml -a ac1 >> output.csv &&
./runProgram.sh -f input/zebra-extension.xml -a ac3 >> output.csv &&
./runProgram.sh -f input/zebra-intension-binary.xml -a ac1 >> output.csv &&
./runProgram.sh -f input/zebra-intension-binary.xml -a ac3 >> output.csv &&
./runProgram.sh -f input/zebra-intension-nonbinary.xml -a ac1 >> output.csv &&
./runProgram.sh -f input/zebra-intension-nonbinary.xml -a ac3 >> output.csv &&
./runProgram.sh -f input/zebra-supports2.xml -a ac1 >> output.csv &&
./runProgram.sh -f input/zebra-supports2.xml -a ac3 >> output.csv