#./runProgram.sh -f input/3queens-conflicts.xml -s BT -u LX >> outputBT.csv &&
#./runProgram.sh -f input/3queens-conflicts.xml -s BT -u LD >> outputBT.csv &&
#./runProgram.sh -f input/3queens-conflicts.xml -s BT -u DEG >> outputBT.csv &&
#./runProgram.sh -f input/3queens-conflicts.xml -s BT -u DD >> outputBT.csv &&
#./runProgram.sh -f input/3queens-intension.xml -s BT -u LX >> outputBT.csv &&
#./runProgram.sh -f input/3queens-intension.xml -s BT -u LD >> outputBT.csv &&
#./runProgram.sh -f input/3queens-intension.xml -s BT -u DEG >> outputBT.csv &&
#./runProgram.sh -f input/3queens-intension.xml -s BT -u DD >> outputBT.csv &&
#./runProgram.sh -f input/4queens-conflicts.xml -s BT -u LX >> outputBT.csv &&
#./runProgram.sh -f input/4queens-conflicts.xml -s BT -u LD >> outputBT.csv &&
#./runProgram.sh -f input/4queens-conflicts.xml -s BT -u DEG >> outputBT.csv &&
#./runProgram.sh -f input/4queens-conflicts.xml -s BT -u DD >> outputBT.csv &&
#./runProgram.sh -f input/4queens-supports.xml -s BT -u LX >> outputBT.csv &&
#./runProgram.sh -f input/4queens-supports.xml -s BT -u LD >> outputBT.csv &&
#./runProgram.sh -f input/4queens-supports.xml -s BT -u DEG >> outputBT.csv &&
#./runProgram.sh -f input/4queens-supports.xml -s BT -u DD >> outputBT.csv &&
#./runProgram.sh -f input/5queens-intension.xml -s BT -u LX >> outputBT.csv &&
#./runProgram.sh -f input/5queens-intension.xml -s BT -u LD >> outputBT.csv &&
#./runProgram.sh -f input/5queens-intension.xml -s BT -u DEG >> outputBT.csv &&
#./runProgram.sh -f input/5queens-intension.xml -s BT -u DD >> outputBT.csv &&
#./runProgram.sh -f input/6queens-conflicts.xml -s BT -u LX >> outputBT.csv &&
#./runProgram.sh -f input/6queens-conflicts.xml -s BT -u LD >> outputBT.csv &&
#./runProgram.sh -f input/6queens-conflicts.xml -s BT -u DEG >> outputBT.csv &&
#./runProgram.sh -f input/6queens-conflicts.xml -s BT -u DD >> outputBT.csv &&
#./runProgram.sh -f input/6queens-intension.xml -s BT -u LX >> outputBT.csv &&
#./runProgram.sh -f input/6queens-intension.xml -s BT -u LD >> outputBT.csv &&
#./runProgram.sh -f input/6queens-intension.xml -s BT -u DEG >> outputBT.csv &&
#./runProgram.sh -f input/6queens-intension.xml -s BT -u DD >> outputBT.csv &&
#./runProgram.sh -f input/20_8_100_20.xml -s BT -u LX >> outputBT.csv &&
#./runProgram.sh -f input/20_8_100_20.xml -s BT -u LD >> outputBT.csv &&
#./runProgram.sh -f input/20_8_100_20.xml -s BT -u DEG >> outputBT.csv &&
#./runProgram.sh -f input/20_8_100_20.xml -s BT -u DD >> outputBT.csv &&
#./runProgram.sh -f input/chain4-conflicts.xml -s BT -u LX >> outputBT.csv &&
#./runProgram.sh -f input/chain4-conflicts.xml -s BT -u LD >> outputBT.csv &&
#./runProgram.sh -f input/chain4-conflicts.xml -s BT -u DEG >> outputBT.csv &&
#./runProgram.sh -f input/chain4-conflicts.xml -s BT -u DD >> outputBT.csv &&
#./runProgram.sh -f input/ColAustralia-conflicts.xml -s BT -u LX >> outputBT.csv &&
#./runProgram.sh -f input/ColAustralia-conflicts.xml -s BT -u LD >> outputBT.csv &&
#./runProgram.sh -f input/ColAustralia-conflicts.xml -s BT -u DEG >> outputBT.csv &&
#./runProgram.sh -f input/ColAustralia-conflicts.xml -s BT -u DD >> outputBT.csv &&
./runProgram.sh -f input/ColAustralia-intension.xml -s BT -u LX >> outputBT.csv &&
./runProgram.sh -f input/ColAustralia-intension.xml -s BT -u LD >> outputBT.csv &&
./runProgram.sh -f input/ColAustralia-intension.xml -s BT -u DEG >> outputBT.csv &&
./runProgram.sh -f input/ColAustralia-intension.xml -s BT -u DD >> outputBT.csv &&
./runProgram.sh -f input/ColK4-conflicts.xml -s BT -u LX >> outputBT.csv &&
./runProgram.sh -f input/ColK4-conflicts.xml -s BT -u LD >> outputBT.csv &&
./runProgram.sh -f input/ColK4-conflicts.xml -s BT -u DEG >> outputBT.csv &&
./runProgram.sh -f input/ColK4-conflicts.xml -s BT -u DD >> outputBT.csv &&
./runProgram.sh -f input/zebra-extension.xml -s BT -u LX >> outputBT.csv &&
./runProgram.sh -f input/zebra-extension.xml -s BT -u LD >> outputBT.csv &&
./runProgram.sh -f input/zebra-extension.xml -s BT -u DEG >> outputBT.csv &&
./runProgram.sh -f input/zebra-extension.xml -s BT -u DD >> outputBT.csv &&
./runProgram.sh -f input/zebra-intension-binary.xml -s BT -u LX  >> outputBT.csv &&
./runProgram.sh -f input/zebra-intension-binary.xml -s BT -u LD >> outputBT.csv &&
./runProgram.sh -f input/zebra-intension-binary.xml -s BT -u DEG >> outputBT.csv &&
./runProgram.sh -f input/zebra-intension-binary.xml -s BT -u DD >> outputBT.csv &&
./runProgram.sh -f input/zebra-supports2.xml -s BT -u LX >> outputBT.csv &&
./runProgram.sh -f input/zebra-supports2.xml -s BT -u LD >> outputBT.csv &&
./runProgram.sh -f input/zebra-supports2.xml -s BT -u DEG >> outputBT.csv &&
./runProgram.sh -f input/zebra-supports2.xml -s BT -u DD >> outputBT.csv