./runProgram.sh -f input/3queens-conflicts.xml -s FC -u dLX >> outputFC.csv &&
./runProgram.sh -f input/3queens-conflicts.xml -s FC -u dLD >> outputFC.csv &&
./runProgram.sh -f input/3queens-conflicts.xml -s FC -u dDEG >> outputFC.csv &&
./runProgram.sh -f input/3queens-conflicts.xml -s FC -u dDD >> outputFC.csv &&
./runProgram.sh -f input/3queens-intension.xml -s FC -u dLX >> outputFC.csv &&
./runProgram.sh -f input/3queens-intension.xml -s FC -u dLD >> outputFC.csv &&
./runProgram.sh -f input/3queens-intension.xml -s FC -u dDEG >> outputFC.csv &&
./runProgram.sh -f input/3queens-intension.xml -s FC -u dDD >> outputFC.csv &&
./runProgram.sh -f input/4queens-conflicts.xml -s FC -u dLX >> outputFC.csv &&
./runProgram.sh -f input/4queens-conflicts.xml -s FC -u dLD >> outputFC.csv &&
./runProgram.sh -f input/4queens-conflicts.xml -s FC -u dDEG >> outputFC.csv &&
./runProgram.sh -f input/4queens-conflicts.xml -s FC -u dDD >> outputFC.csv &&
./runProgram.sh -f input/4queens-supports.xml -s FC -u dLX >> outputFC.csv &&
./runProgram.sh -f input/4queens-supports.xml -s FC -u dLD >> outputFC.csv &&
./runProgram.sh -f input/4queens-supports.xml -s FC -u dDEG >> outputFC.csv &&
./runProgram.sh -f input/4queens-supports.xml -s FC -u dDD >> outputFC.csv &&
./runProgram.sh -f input/5queens-intension.xml -s FC -u dLX >> outputFC.csv &&
./runProgram.sh -f input/5queens-intension.xml -s FC -u dLD >> outputFC.csv &&
./runProgram.sh -f input/5queens-intension.xml -s FC -u dDEG >> outputFC.csv &&
./runProgram.sh -f input/5queens-intension.xml -s FC -u dDD >> outputFC.csv &&
./runProgram.sh -f input/6queens-conflicts.xml -s FC -u dLX >> outputFC.csv &&
./runProgram.sh -f input/6queens-conflicts.xml -s FC -u dLD >> outputFC.csv &&
./runProgram.sh -f input/6queens-conflicts.xml -s FC -u dDEG >> outputFC.csv &&
./runProgram.sh -f input/6queens-conflicts.xml -s FC -u dDD >> outputFC.csv &&
./runProgram.sh -f input/6queens-intension.xml -s FC -u dLX >> outputFC.csv &&
./runProgram.sh -f input/6queens-intension.xml -s FC -u dLD >> outputFC.csv &&
./runProgram.sh -f input/6queens-intension.xml -s FC -u dDEG >> outputFC.csv &&
./runProgram.sh -f input/6queens-intension.xml -s FC -u dDD >> outputFC.csv &&
./runProgram.sh -f input/20_8_100_20.xml -s FC -u dLX >> outputFC.csv &&
./runProgram.sh -f input/20_8_100_20.xml -s FC -u dLD >> outputFC.csv &&
./runProgram.sh -f input/20_8_100_20.xml -s FC -u dDEG >> outputFC.csv &&
./runProgram.sh -f input/20_8_100_20.xml -s FC -u dDD >> outputFC.csv &&
./runProgram.sh -f input/chain4-conflicts.xml -s FC -u dLX >> outputFC.csv &&
./runProgram.sh -f input/chain4-conflicts.xml -s FC -u dLD >> outputFC.csv &&
./runProgram.sh -f input/chain4-conflicts.xml -s FC -u dDEG >> outputFC.csv &&
./runProgram.sh -f input/chain4-conflicts.xml -s FC -u dDD >> outputFC.csv &&
./runProgram.sh -f input/ColAustralia-conflicts.xml -s FC -u dLX >> outputFC.csv &&
./runProgram.sh -f input/ColAustralia-conflicts.xml -s FC -u dLD >> outputFC.csv &&
./runProgram.sh -f input/ColAustralia-conflicts.xml -s FC -u dDEG >> outputFC.csv &&
./runProgram.sh -f input/ColAustralia-conflicts.xml -s FC -u dDD >> outputFC.csv &&
./runProgram.sh -f input/ColAustralia-intension.xml -s FC -u dLX >> outputFC.csv &&
./runProgram.sh -f input/ColAustralia-intension.xml -s FC -u dLD >> outputFC.csv &&
./runProgram.sh -f input/ColAustralia-intension.xml -s FC -u dDEG >> outputFC.csv &&
./runProgram.sh -f input/ColAustralia-intension.xml -s FC -u dDD >> outputFC.csv &&
./runProgram.sh -f input/ColK4-conflicts.xml -s FC -u dLX >> outputFC.csv &&
./runProgram.sh -f input/ColK4-conflicts.xml -s FC -u dLD >> outputFC.csv &&
./runProgram.sh -f input/ColK4-conflicts.xml -s FC -u dDEG >> outputFC.csv &&
./runProgram.sh -f input/ColK4-conflicts.xml -s FC -u dDD >> outputFC.csv &&
./runProgram.sh -f input/zebra-extension.xml -s FC -u dLX >> outputFC.csv &&
./runProgram.sh -f input/zebra-extension.xml -s FC -u dLD >> outputFC.csv &&
./runProgram.sh -f input/zebra-extension.xml -s FC -u dDEG >> outputFC.csv &&
./runProgram.sh -f input/zebra-extension.xml -s FC -u dDD >> outputFC.csv &&
./runProgram.sh -f input/zebra-intension-binary.xml -s FC -u dLX  >> outputFC.csv &&
./runProgram.sh -f input/zebra-intension-binary.xml -s FC -u dLD >> outputFC.csv &&
./runProgram.sh -f input/zebra-intension-binary.xml -s FC -u dDEG >> outputFC.csv &&
./runProgram.sh -f input/zebra-intension-binary.xml -s FC -u dDD >> outputFC.csv &&
./runProgram.sh -f input/zebra-supports2.xml -s FC -u dLX >> outputFC.csv &&
./runProgram.sh -f input/zebra-supports2.xml -s FC -u dLD >> outputFC.csv &&
./runProgram.sh -f input/zebra-supports2.xml -s FC -u dDEG >> outputFC.csv &&
./runProgram.sh -f input/zebra-supports2.xml -s FC -u dDD >> outputFC.csv